# Generated by Django 5.1.6 on 2025-03-02 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FalenciaRecuperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('pedido', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('acesso_documento', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='requerimento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='requerimento',
            name='data_envio',
        ),
        migrations.AddField(
            model_name='requerimento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='requerimentos/'),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='nome_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='tipo_servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='affi.servico'),
        ),
    ]
